name: test
on: [push]
jobs:
  ansible-test:
    runs-on: ubuntu-latest
    steps:
      - name: test
        uses: ansible-community/ansible-test-gh-action@d3a8ec7a59694e25e210fcd44738910149537f0e
        with:
          ansible-core-version: ${{ matrix.ansible-core-version }}
          testing-type: integration
          target: molecule-prometheus-alternative
          pre-test-cmd: env; python -c 'from importlib.metadata import version; print(version("ansible-core"));'
    strategy:
      matrix:
        ansible-core-version: [stable-2.17, stable-2.18]
      fail-fast: false
