name: ansible-test
on: [push]
jobs:
  ansible-test:
    runs-on: ubuntu-latest
    steps:
      - name: pip show ansible-core
        uses: ansible-community/ansible-test-gh-action@d3a8ec7a59694e25e210fcd44738910149537f0e
        with:
          target-python-version: default
          controller-python-version: auto
          ansible-core-version: ${{ matrix.ansible-core-version }}
          docker-image: --docker-privileged
          testing-type: integration
          target: molecule-prometheus-alternative
          coverage: never
          ansible-core-github-repository-slug: ansible/ansible
          collection-root: .
          integration-continue-on-error: true
          integration-diff: true
          integration-retry-on-error: true
          origin-python-version: auto
          pull-request-change-detection: false
          sanity-allow-disabled: false
          pre-test-cmd: pip show ansible-core
    strategy:
      matrix:
        ansible-core-version: [stable-2.17, stable-2.18]
